name: torchkbnufft

channels:
    - anaconda

dependencies:
    - python==3.7
    - pytorch
    - anaconda
    - pip:
        - pyyaml
        - sphinxcontrib-napoleon
        - sphinxcontrib-inlinesyntaxhighlight
        - sphinx.ext.autosummary
        - sphinx.ext.doctest
        - sphinx.ext.intersphinx
        - sphinx.ext.viewcode
        - sphinx.ext.autosectionlabel
